### ISSUE TITLE
请问 LINK_PREVIEW_API_BASE_URL 该如何配置？

### ISSUE THREAD

**Issue by MarlinDiary** [CaliCastle/cali.so#11]
非常喜欢和感谢您的这个开源项目，但在配置 LINK_PREVIEW_API_BASE_URL 时遇到一些问题，不知道该从何处获取该 API。

**Comment by CaliCastle** [comment]
这个是我用来生成链接预览图用的服务，你不需要的话可以：

1. 前往 https://github.com/CaliCastle/cali.so/blob/main/env.mjs#L15 删掉这行
2. 前往 https://github.com/CaliCastle/cali.so/blob/main/components/links/PeekabooLink.tsx#L42-L52 只保留 42-52 行的 JSX，其他多余的 JSX 删除掉
3. 删除 https://github.com/CaliCastle/cali.so/blob/main/app/api/link-preview/route.tsx 文件
4. 完成

**Comment by yaoyaoio** [comment]
@CaliCastle 请问一下 如果不删除对应的代码 如何使用该服务呢？

**Comment by CaliCastle** [comment]
> @CaliCastle 请问一下 如果不删除对应的代码 如何使用该服务呢？

可以前往 urlbox.io 注册，用来生成链接预览的 SaaS 服务，需要收钱的，所以我没写上

**Comment by yaoyaoio** [comment]
> > @CaliCastle 请问一下 如果不删除对应的代码 如何使用该服务呢？
> 
> 可以前往 urlbox.io 注册，用来生成链接预览的 SaaS 服务，需要收钱的，所以我没写上

感谢感谢

**Comment by CaliCastle** [comment]
@yaoyaoio @MarlinDiary 我发布了文章讲解如何配置+部署，感兴趣的话可以看看：
https://cali.so/blog/guide-for-cloning-my-site
