### ISSUE TITLE
请问大佬，vercel部署失败该怎么解决呢

### ISSUE THREAD

**Issue by WanliYa** [CaliCastle/cali.so#13]
Command "pnpm turbo build" exited with 1
部署反复都是这个结果
我填写完env.example后就直接把fork的代码部署到vercel上了
在env.example里填写Vercel必须里的EDGE_CONFIG=""时，我不确定该怎么填写，于是便填了vercel Edge Config Store的id，我不确定是不是和这个有关。

**Comment by CaliCastle** [comment]
这个通过 Vercel 部署的话应该是自动的，在你的 Vercel 项目里可以看到 Edge Config 的 env var。
你可以通过 `vercel env pull` 同步到本地
