### ISSUE TITLE
怎么管理博客文章呢

### ISSUE THREAD

**Issue by Bicheng-G** [CaliCastle/cali.so#14]
首先感恩大神把这么棒的网站开源了！！我只懂一些基础的html和css
我想把这个网站作为自己的个人博客，请问如果要发表新的文章或者管理文章应该怎么操作呢？🙏🏻

**Comment by CaliCastle** [comment]
Hi 我正在写文章教学一步一步的从配置+部署到管理发布文章，估计一两天左右噢

**Comment by CaliCastle** [comment]
@Bicheng-G 文章发布了，可以看看：
https://cali.so/blog/guide-for-cloning-my-site

**Comment by Bicheng-G** [comment]
感恩！谢谢大神🙏🏻

**Comment by Bicheng-G** [comment]
<img width="534" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/df35acd8-0ed0-4bbe-a86e-5e77228b5d17">
<img width="779" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/9d6dfa46-d4b9-4e84-8bb6-d9aa9a2c5191">
@CaliCastle 请问在components/links/PeekabooLink.tsx 第15行，没有找到可以改成false的地方呢

**Comment by Bicheng-G** [comment]
<img width="754" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/31df22eb-0890-4ded-9587-8487f17cc8da">

log如下
<img width="1335" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/164f1c33-5621-4c57-92c3-cd873eb8ce05">
<img width="578" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/6e7afedf-25dd-4101-8ce1-733a2141b9fc">

@CaliCastle 请问这是什么情况呀

**Comment by CaliCastle** [comment]
很明显还是 EDGE_CONFIG 配置不对，按照教程里一步一步走了吗？ @Bicheng-G

**Comment by Bicheng-G** [comment]
教程里EDGE_CONFIG只有改json这一步，感觉不像是json的问题呢。。我看log里是middleware 报错
`[GET] [middleware: "middleware"] / reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true`

**Comment by thejtf** [comment]
> <img alt="image" width="754" src="https://user-images.githubusercontent.com/74954212/253749133-31df22eb-0890-4ded-9587-8487f17cc8da.png">
> log如下 <img alt="image" width="1335" src="https://user-images.githubusercontent.com/74954212/253749246-164f1c33-5621-4c57-92c3-cd873eb8ce05.png"> <img alt="image" width="578" src="https://user-images.githubusercontent.com/74954212/253749335-6e7afedf-25dd-4101-8ce1-733a2141b9fc.png">
> 
> @CaliCastle 请问这是什么情况呀

我也是vercel部署后遇到了这个问题，如下图，请问您是如何解决的啊
![image](https://github.com/CaliCastle/cali.so/assets/10215840/9fa31cdf-9690-4093-8c4f-d2435118463c)

**Comment by Bicheng-G** [comment]
#16

**Comment by thejtf** [comment]
谢谢您的回复，不过我试了添加project问题还是没有得到解决。感谢您的回复。

BICHENG GU ***@***.***> 于2023年7月17日周一 11:19写道：

**Comment by thejtf** [comment]
> @thejtf 应该是project为空引起的，参考这个issue #16 ，在后台添加一个project试试

谢谢您的回复，不过我试了添加project问题还是没有得到解决。感谢您的回复。
