### ISSUE TITLE
请问怎么添加新的social link

### ISSUE THREAD

**Issue by Bicheng-G** [CaliCastle/cali.so#15]
我看了一下源码，没看明白social link的icon是怎么加上去的。 

我发现是Headline文件调用了SociaLink文件，SociaLink又调用了asset里的单独icon文件。

请问如果我想添加一样风格的linkedin图标应该怎么做呀？

**Comment by CaliCastle** [comment]
`SocialLink` 里面有个 `iconMapper` 用来映射域名对应的 icon 可以随意更改

**Comment by Bicheng-G** [comment]
哇 谢谢秒回！我有看到iconMapper是映射域名的，但是不确定到底怎么使用
`
  '(?:linkedin.com)': {
    icon: LinkedinIcon,
    platform: 'linkedin',
    label: 'Linkedin',
  },
`
如果我想加Linkeidn， icon变量如果我没理解错应该是要从asset里import icon文件，我在网上找的linkedin的svg好像没法正常显示

**Comment by CaliCastle** [comment]
> 哇 谢谢秒回！我有看到iconMapper是映射域名的，但是不确定到底怎么使用 `'(?:linkedin.com)': { icon: LinkedinIcon, platform: 'linkedin', label: 'Linkedin', },` 如果我想加Linkeidn， icon变量如果我没理解错应该是要从asset里import icon文件，我在网上找的linkedin的svg好像没法正常显示

可以自己在 assets/icons 文件夹里创建一个 `LinkedInIcon.tsx` 模仿其他的 icon svg 来创建 React component

**Comment by Bicheng-G** [comment]
> > 哇 谢谢秒回！我有看到iconMapper是映射域名的，但是不确定到底怎么使用 `'(?:linkedin.com)': { icon: LinkedinIcon, platform: 'linkedin', label: 'Linkedin', },` 如果我想加Linkeidn， icon变量如果我没理解错应该是要从asset里import icon文件，我在网上找的linkedin的svg好像没法正常显示
> 
> 可以自己在 assets/icons 文件夹里创建一个 `LinkedInIcon.tsx` 模仿其他的 icon svg 来创建 React component

已经解决啦，谢谢大神！我之前也是这样想的，显示不正常是因为svg的原因
