### ISSUE TITLE
Project页面报错

### ISSUE THREAD

**Issue by Bicheng-G** [CaliCastle/cali.so#16]
大神， 请问这个是什么错误呀
<img width="1052" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/d8c2d315-088d-4b52-8312-426905b7f162">
我已经通过/studio 往database里添加了一个project，还是不行。

**Comment by CaliCastle** [comment]
![Tower 3uA3walj@2x](https://github.com/CaliCastle/cali.so/assets/10830749/0d4ef95b-ce1b-4e9a-bb6a-709097e91994)

需要在 Settings 里加哦

**Comment by Bicheng-G** [comment]
> ![Tower 3uA3walj@2x](https://user-images.githubusercontent.com/10830749/253790202-0d4ef95b-ce1b-4e9a-bb6a-709097e91994.png)
> 
> 需要在 Settings 里加哦，编辑完最后记得按 Publish

Aewsome! 谢谢！

**Comment by Bicheng-G** [comment]
<img width="1222" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/a4ca080f-9c87-45f7-a9a5-b57939fc5ece">
@CaliCastle 开发环境感觉都弄好了，pnpm build的时候报错了。请问这个是什么意思呀？我上网找了一圈也没解决

**Comment by CaliCastle** [comment]
看起来是 eslint 出错了

可以本地试试 `pnpm lint —fix` 或者 `pnpm lint — —fix`

**Comment by Bicheng-G** [comment]
<img width="1680" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/49065453-e72a-46f3-8d46-ca1ce9c098d5">

这两个都不行呢

**Comment by Bicheng-G** [comment]
> <img alt="image" width="1680" src="https://user-images.githubusercontent.com/74954212/253791758-49065453-e72a-46f3-8d46-ca1ce9c098d5.png">
> 这两个都不行呢

@CaliCastle 我试了 pnpm --fix，不过还是不行
<img width="1265" alt="image" src="https://github.com/CaliCastle/cali.so/assets/74954212/f2beeeae-785b-495e-85d6-2d3ca28ce135">
这个error code也没说是什么原因。。

**Comment by CaliCastle** [comment]
双 dash fix 不行吗

**Comment by CaliCastle** [comment]
eslint 问题根据 log 修复其实就行了，手动根据错误修也可以的，错误解释的挺清楚的

**Comment by Bicheng-G** [comment]
感恩有求必应！ 🙆🏻‍♂️ 已经成功deploy了
