### ISSUE TITLE
ui/ux: page gets drastically darker when the login modal is activated. 

### ISSUE THREAD

**Issue by l1xiangyi** [CaliCastle/cali.so#18]
![CleanShot 2023-07-21 at 13 14 56@2x](https://github.com/CaliCastle/cali.so/assets/51786539/dd78474d-2eb6-4c43-a124-40e110bc68df)
![CleanShot 2023-07-21 at 13 14 53@2x](https://github.com/CaliCastle/cali.so/assets/51786539/0f75b619-36e9-463c-b353-f0072627dfb9)

The visual might improve if the modal card's color scheme gets closers to the main site's.

**Comment by CaliCastle** [comment]
@l1xiangyi I've modified the background colors a little bit to blend better, should be fixed now.

**Comment by l1xiangyi** [comment]
![CleanShot 2023-07-21 at 15 54 41@2x](https://github.com/CaliCastle/cali.so/assets/51786539/54067e56-b0d2-4933-a82c-cf7f1ec4e1af)
Looks much better now. Amazing design/fixing speed btw！
