### ISSUE TITLE
启动开发服务器后Web报错

### ISSUE THREAD

**Issue by ouyangyanhuo** [CaliCastle/cali.so#20]
![Snipaste_2023-07-25_20-13-34](https://github.com/CaliCastle/cali.so/assets/48152281/caa5b3d3-cfdd-4c06-9db4-a4a57686208e)
如图，这个问题还挺奇怪的，同样的配置，它不影响我在Vercel上部署的内容，在本地就会报错，我已经添加了文章和相关的内容，请问这是为何

**Comment by CaliCastle** [comment]
`pnpm i && pnpm dev`?

**Comment by ouyangyanhuo** [comment]
![Snipaste_2023-07-25_21-54-08](https://github.com/CaliCastle/cali.so/assets/48152281/0c20069b-1638-437c-9b53-3e75c294ea3d)
还是不大行

**Comment by ouyangyanhuo** [comment]
除此之外，build还会引发[#16](https://github.com/CaliCastle/cali.so/issues/16#issuecomment-1637007752) 这个错误，解决方法还没看懂

**Comment by CaliCastle** [comment]
看起来也许是 Windows 的问题，没试过在 Windows 上面运行

**Comment by ouyangyanhuo** [comment]
感谢有求必应！确实是Windows的问题，更换Ubuntu 后就正常了，但是想知道，有没有办法在自己的服务器上运行，而不使用vercel

**Comment by ouyangyanhuo** [comment]
已经解决全部问题，使用 'pnpm build' 之后，再使用 'npm start' 就可以使用了

**Comment by ouyangyanhuo** [comment]
看来我再此遇到了这个问题，并且是在Linux中
我在完成 Sanity 的依赖安装后，就会出现这个问题，依旧是/studio可以访问，Vercel、本地都可以，但是它们的界面居然还有所不同
![Snipaste_2023-07-27_19-17-29](https://github.com/CaliCastle/cali.so/assets/48152281/10201f0a-597c-4112-ad96-d97aa8e85581)
![Snipaste_2023-07-27_19-17-37](https://github.com/CaliCastle/cali.so/assets/48152281/8767db7a-7188-4e82-99af-b8a225632a4c)
内容更多的是 Vercel，但是它们 Sanity 的版本甚至都是相同的，不知这是为何。

环境：
Node.js v18.17.0、NPM v9.8.1、PNPM v8.6.10、Ubuntu20(WSL)
后台 Sanity 版本显示均为 v3.12.2
复现步骤：

1. 克隆仓库
2. pnpm i
3. 'npm create sanity@latest -- --template clean --create-project "Cali Demo" --dataset production'
4. 配置其它内容
5. pnpm dev
在第三步中，所有内容均填为yes，template为blog，最后输入为/studio
就会出现启动开发服务器后，Web报错的问题，并且在 Vercel 部署的 /studio 和 localhost 的/studio 有所不同

**Comment by CaliCastle** [comment]
在运行创建 sanity 项目的时候不要回答任何问题，开始问第一个问题时直接 Ctrl C 退出

**Comment by ouyangyanhuo** [comment]
![Snipaste_2023-07-27_20-59-32](https://github.com/CaliCastle/cali.so/assets/48152281/2d3f6789-12ad-4c72-a3c1-e0f47ceac7c0)
![Snipaste_2023-07-27_20-59-55](https://github.com/CaliCastle/cali.so/assets/48152281/f1ef98d0-5f39-4270-8068-ffbc22c26fc5)
看起来，它好像出现了更无法解释的错误
