### ISSUE TITLE
更新NextJS

### ISSUE THREAD

**Issue by Bicheng-G** [CaliCastle/cali.so#21]
大佬你好，我之前在换svg favicon的时候遇到了问题。搜了一圈发现nextJs五天前的[更新](https://github.com/vercel/next.js/releases/tag/v13.4.12)解决了[这个问题](https://github.com/vercel/next.js/pull/52609)。

我尝试在本地run pnpm install next@latest 更新Next，结果本来能build的，更新后一堆报错。我没搞懂具体是哪里有问题。

希望大佬能抽空指点一下。

**Comment by CaliCastle** [comment]
已在 #46 更新到 14.1
