### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information). Digest: 477354927

### ISSUE THREAD

**Issue by Benn314** [CaliCastle/cali.so#22]
在本地可以启动项目但部署到vercel会报错，控制台报错信息： Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error. 我不知道这个问题应该怎么解决

**Comment by CaliCastle** [comment]
> 大概率是我们第一次部署但是没有发布文章导致的，首页需要加载 post，但是没有加上这个 posts 为空的处理🐛，修改 `app/(main)/blog/BlogPosts.tsx` 如下：
> 
> ```ts
> export async function BlogPosts({ limit = 5 }) {
>   const posts = await getLatestBlogPosts({ limit, forDisplay: true })
> 
>   if (posts.length === 0) {
>     return (<strong>🏃 我的文章很快就会发布，不要着急！</strong>)
>   }
> 
>   const postIdKeys = posts.map(({ _id }) => kvKeys.postViews(_id))
>   ...
> }
> ```
> 
> 即 **posts 为空的话直接返回一个提示内容**。
> 
> 其实， `/projects` 页面也有类似的问题，如果没有在 studio 的 Settings 中添加项目内容，本地运行和部署后也会显示不了，同样需要添加为 null 的处理，修改 `app/(main)/projects/Projects.tsx`:
> 
> ```ts
> export async function Projects() {
>   const { projects } = await getSettings()
> 
>   return (projects ? 
>     <ul
>       role="list"
>       className="grid grid-cols-1 gap-x-12 gap-y-16 sm:grid-cols-2 lg:grid-cols-3"
>     >
>       {projects.map((project) => (
>         <ProjectCard project={project} key={project._id} />
>       ))}
>     </ul> : <strong>🔥 产品和项目很多，待我慢慢更新！</strong>
>   )
> }
> ```
> 
> @Benn314 @CaliCastle

哈哈感谢提出解决方案，的确我在写的时候没想过会直接给别人拿来建站，所以空数据的时候也没考虑进去 🙏

后续我会统一优化一下

**Comment by Benn314** [comment]
好嘞✔




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CaliCastle/cali.so"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月14日(星期四) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CaliCastle/cali.so] Application error: a client-side exception has occurred (see the browser console for more information). Digest: 477354927 (Issue #22)





  
大概率是我们第一次部署但是没有发布文章导致的，首页需要加载 post，但是没有加上这个 posts 为空的处理🐛，修改 app/(main)/blog/BlogPosts.tsx 如下：
 export async function BlogPosts({ limit = 5 }) {   const posts = await getLatestBlogPosts({ limit, forDisplay: true })   if (posts.length === 0) {     return (<strong&gt;🏃 我的文章很快就会发布，不要着急！</strong&gt;)   }   const postIdKeys = posts.map(({ _id }) =&gt; kvKeys.postViews(_id))   ... }
 
即 posts 为空的话直接返回一个提示内容。
 
其实， /projects 页面也有类似的问题，如果没有在 studio 的 Settings 中添加项目内容，本地运行和部署后也会显示不了，同样需要添加为 null 的处理，修改 app/(main)/projects/Projects.tsx:
 export async function Projects() {   const { projects } = await getSettings()   return (projects ?      <ul       role="list"       className="grid grid-cols-1 gap-x-12 gap-y-16 sm:grid-cols-2 lg:grid-cols-3"     &gt;       {projects.map((project) =&gt; (         <ProjectCard project={project} key={project._id} /&gt;       ))}     </ul&gt; : <strong&gt;🔥 产品和项目很多，待我慢慢更新！</strong&gt;   ) }
 
@Benn314 @CaliCastle
  
哈哈感谢提出解决方案，的确我在写的时候没想过会直接给别人拿来建站，所以空数据的时候也没考虑进去 🙏
 
后续我会统一优化一下

**Comment by wangpangzier** [comment]
> 大概率是我们第一次部署但是没有发布文章导致的，首页需要加载 post，但是没有加上这个 posts 为空的处理🐛，修改 `app/(main)/blog/BlogPosts.tsx` 如下：
> 
> ```ts
> export async function BlogPosts({ limit = 5 }) {
>   const posts = await getLatestBlogPosts({ limit, forDisplay: true })
> 
>   if (posts.length === 0) {
>     return (<strong>🏃 我的文章很快就会发布，不要着急！</strong>)
>   }
> 
>   const postIdKeys = posts.map(({ _id }) => kvKeys.postViews(_id))
>   ...
> }
> ```
> 
> 即 **posts 为空的话直接返回一个提示内容**。
> 
> 其实， `/projects` 页面也有类似的问题，如果没有在 studio 的 Settings 中添加项目内容，本地运行和部署后也会显示不了，同样需要添加为 null 的处理，修改 `app/(main)/projects/Projects.tsx`:
> 
> ```ts
> export async function Projects() {
>   const { projects } = await getSettings()
> 
>   return (projects ? 
>     <ul
>       role="list"
>       className="grid grid-cols-1 gap-x-12 gap-y-16 sm:grid-cols-2 lg:grid-cols-3"
>     >
>       {projects.map((project) => (
>         <ProjectCard project={project} key={project._id} />
>       ))}
>     </ul> : <strong>🔥 产品和项目很多，待我慢慢更新！</strong>
>   )
> }
> ```
> 
> @Benn314 @CaliCastle

我这里按照教程部署之后，点击「项目」菜单汇报这个错误。
Application error: a client-side exception has occurred （see the browser consale for more information）.
Digest:2519062493

按照@okooo5km 提出的方案修改重新部署之后，还是会有问题，也不知道什么原因。可以帮忙看一下吗？

**Comment by CaliCastle** [comment]
现在应该已经没有这个问题了，我重新用新账号部署实验了一下，已验证
