### ISSUE TITLE
留言墙无法留言

### ISSUE THREAD

**Issue by ben-fang** [CaliCastle/cali.so#28]
发起留言时提示 Application error: a client-side exception has occurred (see the browser console for more information).
怀疑是Clerk未反馈正确的imageUrl
![image](https://github.com/CaliCastle/cali.so/assets/43346493/046e397e-a55c-4bc6-a6ff-8c75f65cdcbc)

**Comment by CCKNBC** [comment]
同问，API部分为什么报400

**Comment by CaliCastle** [comment]
看样子是没拿到用户数据？

**Comment by CCKNBC** [comment]
> 看样子是没拿到用户数据？

现在能留言了，但是 反应还是无法点击
![image](https://github.com/CaliCastle/cali.so/assets/62093618/ce2f33a0-9c38-4711-af93-9bfa1dd70d8f)

以及我不确定 Clerk 使用测试环境，而不是生产环境会不会有影响
麻烦大佬帮忙看看
https://www.ccknbc.cc/blog/test-post

另外我不知道为什么 重新部署后 在数据库没被改动 也没看到攻击迹象的情况下，反应和访问量突然变为 万，我毫无头绪，重新部署也没用

**Comment by CCKNBC** [comment]
抱歉 打扰了 https://www.vercel-status.com/
好像是 Vercel 的故障，等他们修复后重新部署应该可以解决

**Comment by ben-fang** [comment]
那我之后也试着重新部署一遍吧，是Clerk和Vercel都要重新部署？

**Comment by CCKNBC** [comment]
> 那我之后也试着重新部署一遍吧，是Clerk和Vercel都要重新部署？

就是 Resend 那里有个要注意的点，需要验证域名，然后修改email.ts 里为对应的，不然会卡在邮件发送那里，导致报错

我是在另一个 issue 看到的

Clerk 应该不用，到时候 Vercel 重新部署再试试看吧

我就说为什么 访问量变成随机，反应全变成万

**Comment by CaliCastle** [comment]
> > 看样子是没拿到用户数据？
> 
> 
> 
> 现在能留言了，但是 反应还是无法点击
> 
> ![image](https://github.com/CaliCastle/cali.so/assets/62093618/ce2f33a0-9c38-4711-af93-9bfa1dd70d8f)
> 
> 
> 
> 以及我不确定 Clerk 使用测试环境，而不是生产环境会不会有影响
> 
> 麻烦大佬帮忙看看
> 
> https://www.ccknbc.cc/blog/test-post
> 
> 
> 
> 另外我不知道为什么 重新部署后 在数据库没被改动 也没看到攻击迹象的情况下，反应和访问量突然变为 万，我毫无头绪，重新部署也没用
> 
> 

我晚点看看 👌

**Comment by CaliCastle** [comment]
所以是解决了？

**Comment by ben-fang** [comment]
> 所以是解决了？

问题没解决，把email.ts和Resend都配置好之后还是报Client-Side Error，但现在手边没有电脑，没办法定位问题。
Vercel那边现在确实提示Edge Function运行存在问题，不排除这种可能性。

**Comment by CCKNBC** [comment]
> 我晚点看看 👌

我在试着重新部署，然后我点击了一下，反应能变成正常值，但刷新后还是显示异常;访问量，的话还是异常

![image](https://github.com/CaliCastle/cali.so/assets/62093618/76dcc54b-3676-43d0-a9ed-829bafdc9692)

**Comment by CCKNBC** [comment]
不好意思 找到原因了 环境变量忘记改回来了
VERCEL_ENV === 'production'

**Comment by ben-fang** [comment]
> 所以是解决了？

我这边Resend已经配置好了，但报错信息还是这个
![image](https://github.com/CaliCastle/cali.so/assets/43346493/750926ae-67ff-41c7-a0bd-04ff8e007313)

**Comment by CaliCastle** [comment]
> 不好意思 找到原因了 环境变量忘记改回来了 VERCEL_ENV === 'production'

本地开发看到的访问量是模拟随机的

**Comment by CCKNBC** [comment]
> > 不好意思 找到原因了 环境变量忘记改回来了 VERCEL_ENV === 'production'
> 
> 本地开发看到的访问量是模拟随机的

看到错误相关代码，我马上明白了环境变量复制粘贴忘记改过来了，还好没新开一个 issue
目前一切正常，就期待更多优化了

**Comment by CaliCastle** [comment]
> > 所以是解决了？
> 
> 我这边Resend已经配置好了，但报错信息还是这个 ![image](https://private-user-images.githubusercontent.com/43346493/292669921-750926ae-67ff-41c7-a0bd-04ff8e007313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mjc5NDIsIm5iZiI6MTcwMzQyNzY0MiwicGF0aCI6Ii80MzM0NjQ5My8yOTI2Njk5MjEtNzUwOTI2YWUtNjdmZi00MWM3LWEwYmQtMDRmZjhlMDA3MzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE0MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjg2ZWI4ZWEwNTY3NzZlNzZiM2U3NTE1Yzg5ZDM0YThjMjNmZGE5ZDNlYWUyOTUyOWRmMjhkY2I3MGUzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CE34gHKcdyYtAO-a8iQmzefU3Vu30ddrkMxQrjSNtwU)

这个感觉很明显是 Clerk 的配置有问题，要不然不会拿不到用户数据

**Comment by ben-fang** [comment]
> > > 所以是解决了？
> > 
> > 
> > 我这边Resend已经配置好了，但报错信息还是这个 ![image](https://private-user-images.githubusercontent.com/43346493/292669921-750926ae-67ff-41c7-a0bd-04ff8e007313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mjc5NDIsIm5iZiI6MTcwMzQyNzY0MiwicGF0aCI6Ii80MzM0NjQ5My8yOTI2Njk5MjEtNzUwOTI2YWUtNjdmZi00MWM3LWEwYmQtMDRmZjhlMDA3MzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE0MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjg2ZWI4ZWEwNTY3NzZlNzZiM2U3NTE1Yzg5ZDM0YThjMjNmZGE5ZDNlYWUyOTUyOWRmMjhkY2I3MGUzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CE34gHKcdyYtAO-a8iQmzefU3Vu30ddrkMxQrjSNtwU)
> 
> 这个感觉很明显是 Clerk 的配置有问题，要不然不会拿不到用户数据

但我确实再三检查过Clerk的配置，没有问题，难道是因为用的是Production Mode？

**Comment by ben-fang** [comment]
> > > > 所以是解决了？
> > > 
> > > 
> > > 我这边Resend已经配置好了，但报错信息还是这个 ![image](https://private-user-images.githubusercontent.com/43346493/292669921-750926ae-67ff-41c7-a0bd-04ff8e007313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mjc5NDIsIm5iZiI6MTcwMzQyNzY0MiwicGF0aCI6Ii80MzM0NjQ5My8yOTI2Njk5MjEtNzUwOTI2YWUtNjdmZi00MWM3LWEwYmQtMDRmZjhlMDA3MzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE0MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjg2ZWI4ZWEwNTY3NzZlNzZiM2U3NTE1Yzg5ZDM0YThjMjNmZGE5ZDNlYWUyOTUyOWRmMjhkY2I3MGUzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CE34gHKcdyYtAO-a8iQmzefU3Vu30ddrkMxQrjSNtwU)
> > 
> > 
> > 这个感觉很明显是 Clerk 的配置有问题，要不然不会拿不到用户数据
> 
> 但我确实再三检查过Clerk的配置，没有问题，难道是因为用的是Production Mode？

如果真的是Clerk配置的问题，那评论功能也应该拿不到用户数据，但现在评论功能是正常的

**Comment by CaliCastle** [comment]
你本地能复现吗 @ben-fang

**Comment by ben-fang** [comment]
> 你本地能复现吗 @ben-fang

本地无法复现，本地只能Development Mode，这种情况下Clerk也用Development Mode是没有问题的，但Vercel那边不论是Development还是Production都是同样的问题

**Comment by CaliCastle** [comment]
@ben-fang 那你私聊我 TG or Discord 你的 clerk 设置看看
