### ISSUE TITLE
admin页面新建newsletters报错，和留言墙报错 。实在不明白  

### ISSUE THREAD

**Issue by laogou717** [CaliCastle/cali.so#34]
### **admin新建newsletters问题**
![a75d9a24f6752ebc38d657e57958cb8](https://github.com/CaliCastle/cali.so/assets/128354383/2c1cf178-073f-4ace-92ba-cb781a9d122a)
![efcf1323edb29f65d70bf2f47d01ae4](https://github.com/CaliCastle/cali.so/assets/128354383/77ea629e-ae62-4871-9ea0-ac36d365c754)

**### 留言墙报错问题**
![a6b89204bdbb57349fd567db864a032](https://github.com/CaliCastle/cali.so/assets/128354383/1c7aaefe-4c01-41c0-93b2-ba901e96c4ee)
![1cc74cc27737efaab7f94adb642048e](https://github.com/CaliCastle/cali.so/assets/128354383/5086a107-fafe-4344-b915-814d1b657292)

**Comment by laogou717** [comment]
而且现在发现，登录和退出登录会自动重定向到您的网址里
![30df7158e1db5a71fa2630407b8ac04](https://github.com/CaliCastle/cali.so/assets/128354383/eeceae00-acae-4048-b103-83114ce00889)
![96bede660f59fe78747af349b5457cf](https://github.com/CaliCastle/cali.so/assets/128354383/7c49961d-fd98-43f1-8568-a88e36e100e4)

**Comment by laogou717** [comment]
再补充一下,我在本地部署是完全没问题的

**Comment by CaliCastle** [comment]
是什么原因呢

**Comment by laogou717** [comment]
> 是什么原因呢
感谢大大回复，我犯了个低级错误，没有去更改config中的[email.ts](https://github.com/CaliCastle/cali.so/blob/main/config/email.ts)
![image](https://github.com/CaliCastle/cali.so/assets/128354383/1f2cbcd7-d449-43b3-a1a1-f554ea8645a0)
导致在[resend](https://resend.com/)尝试发送通知邮件时，它会尝试用您的域名进行发送，所以自然的失败了。目前已经解决了。
### 🤔发现了另一些问题
##当我在/studio中编辑任意POST时，在正文部分添加Code Block ，
![image](https://github.com/CaliCastle/cali.so/assets/128354383/3f8446cf-7377-4722-9c8f-85d04d9703d4)
![image](https://github.com/CaliCastle/cali.so/assets/128354383/f5e453a2-fdba-4cb7-8638-cf0d723e0ed1)
##代码填写：`<button type="button">点击我</button>`,然后这时只需选择HTML就会立马崩溃，并且**再也无法编辑这个POST**进行更正，我只能删除数据库重新添加内容。问了GPT它说要在其他地方添加代码，但我不太懂，希望大大能指点一下
![image](https://github.com/CaliCastle/cali.so/assets/128354383/e39c9990-3d26-49d8-9424-0a9020866021)
![image](https://github.com/CaliCastle/cali.so/assets/128354383/f7b16886-72fe-4ac5-83c4-2a2180e34baa)
![image](https://github.com/CaliCastle/cali.so/assets/128354383/d3df5631-b291-4557-963d-01968be59712)

**Comment by CCKNBC** [comment]
感谢🙏

**Comment by laogou717** [comment]
> > 是什么原因呢
> > 感谢大大回复，我犯了个低级错误，没有去更改config中的[email.ts](https://github.com/CaliCastle/cali.so/blob/main/config/email.ts)
> > ![image](https://private-user-images.githubusercontent.com/128354383/292401460-1f2cbcd7-d449-43b3-a1a1-f554ea8645a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDAxNDYwLTFmMmNiY2Q3LWQ0NDktNDNiMy1hMWExLWY1NTRlYTg2NDVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmNlYzI0YjUyMWJlNjkxZGM4YTdmNjQxOTRkMTY4ZTQwMmExOGQ2NDA0OTI2MTU0ZDM3NThkMDRjNDc5NWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.waGWHGp5SHq8snWHKprCFNrShBrnR2vZyAM4WozYbYA)
> > 导致在[resend](https://resend.com/)尝试发送通知邮件时，它会尝试用您的域名进行发送，所以自然的失败了。目前已经解决了。
> 
> ### 🤔发现了另一些问题
> ##当我在/studio中编辑任意POST时，在正文部分添加Code Block ， ![image](https://private-user-images.githubusercontent.com/128354383/292408621-3f8446cf-7377-4722-9c8f-85d04d9703d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDA4NjIxLTNmODQ0NmNmLTczNzctNDcyMi05YzhmLTg1ZDA0ZDk3MDNkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWVhZWNhMTMwNjUxZmU5NDU4NGQ5MTdiNDQ0NWZlM2FlOWIyNWMyZTMyMWZlNzVlM2E4Y2FiZjYyMzcxYjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6YsIuPA1dOXnXQPFlBZoDpuwcPXNhFxTCTruS35DOw) ![image](https://private-user-images.githubusercontent.com/128354383/292409007-f5e453a2-fdba-4cb7-8638-cf0d723e0ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDA5MDA3LWY1ZTQ1M2EyLWZkYmEtNGNiNy04NjM4LWNmMGQ3MjNlMGVkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTE4YjkwNDQxZDg5YTc3YzVlZTVlNWM2MjAwMDk1YjZjZWUxOTMyYmU2MzE2YmNiNTliODYwODkxNjk1YmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.idwsSQd3mXzis7deEhYgalH0Tic6Vr2XKGoCpcjlNfk) ##代码填写：`<button type="button">点击我</button>`,然后这时只需选择HTML就会立马崩溃，并且**再也无法编辑这个POST**进行更正，我只能删除数据库重新添加内容。问了GPT它说要在其他地方添加代码，但我不太懂，希望大大能指点一下 ![image](https://private-user-images.githubusercontent.com/128354383/292410418-e39c9990-3d26-49d8-9424-0a9020866021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDEwNDE4LWUzOWM5OTkwLTNkMjYtNDlkOC05NDI0LTBhOTAyMDg2NjAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmNiMjZjZTViNmVlN2YwOGJmOWYxYTFmMGY4NzBiMzYyNWNlNTA1OTliOTk5NmZhYjQ3Y2NkMzY2NmE5ODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3V7QksY5IedFmKLqlA2-RnbEtf3YWUwAuOPGlkHq7g) ![image](https://private-user-images.githubusercontent.com/128354383/292409941-f7b16886-72fe-4ac5-83c4-2a2180e34baa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDA5OTQxLWY3YjE2ODg2LTcyZmUtNGFjNS04M2M0LTJhMjE4MGUzNGJhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAzZDVlNjc1MDZiYWVkZjA5N2ZiNWFhMTEwNjU3YTliNjBhMzNlMGQyNWQ0NTBlMWYzNWYyNTJiZTI5MzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sCxFMQyjrG_t2kIjtkdUUz6JiS_JajQnFddveFGE2d4) ![image](https://private-user-images.githubusercontent.com/128354383/292411824-d3df5631-b291-4557-963d-01968be59712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTE4NDQsIm5iZiI6MTcwMzM1MTU0NCwicGF0aCI6Ii8xMjgzNTQzODMvMjkyNDExODI0LWQzZGY1NjMxLWIyOTEtNDU1Ny05NjNkLTAxOTY4YmU1OTcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNzEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDY0YTAxMDg1NmYxYjk3NmYxY2NjN2RhMWFjOTA0MjNiODM3MjcyMmYzZDBjNTkzMDg3MzAxNWY3MWVkM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WLD16EGEZ-wbBctdYHksa7fSdiVXnC4XFt514T5tMGQ)

### 防止有人跟我遇到一样的问题
<img width="642" alt="image" src="https://github.com/CaliCastle/cali.so/assets/128354383/970209f1-d4a8-441a-936d-88ef4c753161">
原因就是不支持嵌入这个类型的代码,如果有人跟我一样好奇的尝试了,然后没办法编辑或删除了
### 可以在本地用cmd或者Mac终端用Sanity CLI来管理删除它[下面是MAC终端的简单演示]
要在Mac的终端上使用Sanity CLI来操作Sanity Studio中的内容，您需要按照以下步骤操作：

1. **安装Sanity CLI**:
如果没有安装Sanity CLI，可以通过npm（需要有Node.js和npm在您的系统上）来安装。
打开终端并运行以下命令：
   ```sh
   npm install -g @sanity/cli
   ```
2. **登录Sanity账户**:
安装完Sanity CLI后，在终端中使用以下命令登录到您的Sanity账户：
   ```sh
   sanity login
   ```

3. **启动Sanity Studio**：在项目目录中，运行下面的命令来启动Sanity Studio：
   ```sh
   sanity start
   ```
4. **访问Sanity Studio**：Sanity Studio将在本地服务器上启动，通常是在 `http://localhost:3333`。使用您的浏览器访问这个地址，应该能够看到Sanity Studio的界面。
