### ISSUE TITLE
Error：ERR wrong number of arguments for 'mget' command

### ISSUE THREAD

**Issue by cczywyc** [CaliCastle/cali.so#37]
PR #35 合入后，当 post 为空时，直接在生产环境（production）下启动（或部署）会报错：ERR wrong number of arguments for 'mget' command。
<img width="999" alt="截屏2023-12-23 23 27 37" src="https://github.com/CaliCastle/cali.so/assets/48176229/75243ff0-0f1b-4eda-8b70-53f5da6fd7bb">

**Comment by CaliCastle** [comment]
你有几个 post？

**Comment by cczywyc** [comment]
> 你有几个 post？

现在没有 post，直接生产环境启动，所以 postIdKeys.length 为 0，不符合 redit.mget() 参数的长度

**Comment by cczywyc** [comment]
所以在 BlogPosts.tsx 中，我认为一个可以的修改方式为：
`let views: number[] = []
  if (env.VERCEL_ENV === 'development') {
    views = posts.map(() => Math.floor(Math.random() * 1000))
  } else {
    if (postIdKeys.length > 0) {
      views = await redis.mget<number[]>(...postIdKeys)
    }
  }`
大佬您看看？ @CaliCastle

**Comment by CaliCastle** [comment]
是的，因为这个导致的，是一个解决方案
