### ISSUE TITLE
mysql自己的数据库怎么设置呢

### ISSUE THREAD

**Issue by jw-star** [CaliCastle/cali.so#41]

**Comment by ryangee23** [comment]
@jw-star  你好，你是已经解决了这个问题了吗？我看你关闭了这个issue，我也有同样的需求。

**Comment by ryangee23** [comment]
OK了，照着drizzle orm官网自己摸索着解决了。
目前MySQL数据库是用的自己云服务器的数据库。
planetscale没有信用卡没法继续操作下去了。

**Comment by adminlove520** [comment]
.env里面  DATABASE_URL=""这个参数是啥呀  然后就是库名为啥没有呀   能不能出一个demo配置文件呀

**Comment by lemondy** [comment]
同样的问题，买了腾讯云的数据库，还没修改好😭

**Comment by lemondy** [comment]
> OK了，照着drizzle orm官网自己摸索着解决了。 目前MySQL数据库是用的自己云服务器的数据库。 planetscale没有信用卡没法继续操作下去了。

请问你是怎么修改的了？

**Comment by lemondy** [comment]
> 同样的问题，买了腾讯云的数据库，还没修改好😭

<img width="742" alt="image" src="https://github.com/CaliCastle/cali.so/assets/7106392/81570d44-6966-486b-959b-c96dc25dcd14">
解决了，不实用url，直接使用用户名密码可以访问了

**Comment by CaliCastle** [comment]
原理是一样的，自己在连接数据库的 DATABASE_URL 改成自己的即可
