### ISSUE TITLE
sanity getSetting 为null

### ISSUE THREAD

**Issue by BlackBerry009** [CaliCastle/cali.so#49]
翻看了代码这里没有处理null的情况，是一定有值吗，（或许我配置的姿势不对
![image](https://github.com/CaliCastle/cali.so/assets/42471741/539b6956-42fd-4c71-a0d4-6753b1fc8315)

**Comment by BlackBerry009** [comment]
需要在/studio 初始化。

**Comment by weilirs** [comment]
请问怎么在/studio 初始化？我也遇到了这个问题但视频里好像没提到，谢谢！

**Comment by BlackBerry009** [comment]
> 请问怎么在/studio 初始化？我也遇到了这个问题但视频里好像没提到，谢谢！

在/studio中，进行网站配置、博客配置即可

**Comment by weilirs** [comment]
哦我设置好了现在可以了，谢谢！
