### ISSUE TITLE
guestbook client crash

### ISSUE THREAD

**Issue by CaliCastle** [CaliCastle/cali.so#9]
![image](https://github.com/CaliCastle/cali.so/assets/10830749/4e9adafa-b1c1-40a1-8d82-238a7b6668f2)

Reported from Twitter

**Comment by CaliCastle** [comment]
Looks like it's coming from Clerk...
Can't repro once, might be an internet issue

**Comment by laogou717** [comment]
<img width="2353" alt="image" src="https://github.com/CaliCastle/cali.so/assets/128354383/e65d7dbb-d112-449c-85b2-0f2b200f7890">
我一直是这样,但我不知道应该更改哪里
